### ISSUE TITLE
`pyassimp.errors.AssimpError: assimp library not found`

### ISSUE THREAD

**Issue by ericaweng** [CMU-TBD/SocNavBench#14]
I'm trying to set up the environment (`INSTALLATION.md`), and I get an error when running `PYOPENGL_PLATFORM=egl PYTHONPATH='.' python tests/generate_traversibles.py` to generate map files:
  ```
File ".../.miniconda3/envs/socnavbench/lib/python3.6/site-packages/pyassimp/core.py", line 38, in AssimpLib
    load, load_mem, export, release, dll = helper.search_library()
  File ".../.miniconda3/envs/socnavbench/lib/python3.6/site-packages/pyassimp/helper.py", line 245, in search_library
    raise AssimpError("assimp library not found")
pyassimp.errors.AssimpError: assimp library not found
```

- I tried deleting the environment, updating my conda to the latest version (using `conda update -n base -c defaults conda`), and reinstalling; same error message.
- I get the success messages `HUNK #3 succeeded at 401 (offset 1 line). Hunk #4 succeeded at 407 (offset 1 line)`.after running `bash patches/apply_patches_3.sh`, both before and after applying the `pyassimp` bug patch, as expected.
- I tried pip installing `pyassimp==4.1.4` (the lastest version) just to see what would happen -- same error.
- I tried `import pyassimp` in the interpreter (`python=3.6.9`) and get the exact same `pyassimp.errors.AssimpError: assimp library not found `error. The error actually also occurs in the interpreter before applying any patches.

I'm wondering if you have ever come across this error? Could it be a problem with pyassimp or the conda env library structure?
Thanks so much.

**Comment by GustavoSilvera** [comment]
Hmm. Did you install `libassimp-dev`? This should allow you to have the assimp library on Linux.

**Comment by ericaweng** [comment]
Yes, this worked, thank you! I apologize, I must have missed that line in the README.
