### ISSUE TITLE
Install pip for python 3.5

### ISSUE THREAD

**Issue by ericaweng** [CMU-TBD/SocNavBench#16]
Install pip line in [this readme](https://github.com/CMU-TBD/SocNavBench/blob/master/surreal/README.md#212-blender) should be changed from:
`wget https://bootstrap.pypa.io/get-pip.py`
to:
`wget https://bootstrap.pypa.io/pip/3.5/get-pip.py`

**Comment by GustavoSilvera** [comment]
Thanks for noting this! We've added it to our documentation and it will be updated soon.
