### ISSUE TITLE
How to generate the 2-D laser scan from the perspective of the robot at each time step?

### ISSUE THREAD

**Issue by tcjcxy30** [CMU-TBD/SocNavBench#2]
Hi:
    Thank you very much for your work. I need your help with two questions.
    1. I want to know how to generate the laser scan from the perspective of the robot at each time step in the project?
    2. Can you provide the tested data of SFM, ORCA, CADRL in Fig.6 of the paper "SocNavBench"? 
    Thanks again.

**Comment by ajdroid** [comment]
Thanks for your interest,

1. We don't support laser scans, but a full RGBD image can be generated which you may be able to sample for a laser scan depending on the spec you want.
2. What do you mean by tested data here? Are you asking about the trajectories generated by those algorithms?

**Comment by tcjcxy30** [comment]
> Thanks for your interest,
> 
> 1. We don't support laser scans, but a full RGBD image can be generated which you may be able to sample for a laser scan depending on the spec you want.
> 2. What do you mean by tested data here? Are you asking about the trajectories generated by those algorithms?

Thanks for your reply.
    1. I will try to do that, thank you.
    2. I want to use these algorithms (SFM, ORCA, CADRL) as benchmarks, just like what you did in your paper "SocNavBench". So can you provide all the test results of these methods?

**Comment by ajdroid** [comment]
Ah I think I understand, for your q2, if you want the average values for all the metrics for the baseline methods, you should be able to use the values in the tables 2-4. If you want more details than that, such as the distribution of the metrics which we showed in the violin plots, I can also get you that trajectory data but it'll take a few days.
